---
title: "code_Xinyan"
author: "Xinyan Zheng"
date: "December 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(leaps)

#load the data
data_bwd = read.csv("./data/cleaned_data_for_analyses.csv") %>% 
  select(-X, -postalcode,-facilityname,-facilityzip, -patientid, -visitid, -date) %>% 
  mutate(is30dayreadmit = as.factor(is30dayreadmit), icu_flag = as.factor(icu_flag))
str(data_bwd)

```

```{r}
# using the selected variable from automatic method and go on using criterion-based method
attach(data_bwd)
model_bw <- lm(log_length_of_stay ~ is30dayreadmit + evisit + age 
                           + gender + maritalstatus + insurancetype
                           + heartrate_transformed + respirationrate_transformed 
                           + mean_arterial_pressure)
model_fw <- lm(log_length_of_stay ~ is30dayreadmit + evisit + age 
                           + race + insurancetype + heartrate_transformed 
                           + respirationrate_transformed + mean_arterial_pressure)

# for model yield from backward elimination method
criterion_bw <- regsubsets(log_length_of_stay ~ is30dayreadmit + evisit + age 
                           + gender + maritalstatus + insurancetype
                           + heartrate_transformed + respirationrate_transformed 
                           + mean_arterial_pressure, data=data_bwd, nvmax = 10)
res_bw<-summary(criterion_bw)
par(mfrow=c(2,2))
plot(1:10, res_bw$cp, xlab="No of parameters", ylab="Cp Statistic", main = " Cp Statisticof model from bw")
abline(0,1)
plot(1:10, res_bw$adjr2, xlab="No of parameters", ylab="Adj R2", main = " Adj R2 of model from bw" )
plot(1:10, res_bw$rss, xlab="No of parameters", ylab="rss", main = " rss of model from bw")
plot(1:10, res_bw$bic, xlab="No of parameters", ylab="bic",main = " bic of model from bw")

# for model yield from forward elimination method
criterion_fw <- regsubsets(log_length_of_stay ~ is30dayreadmit + evisit + age 
                           + race + insurancetype + heartrate_transformed 
                           + respirationrate_transformed + mean_arterial_pressure, data=data_bwd, nvmax = 9)
res_fw<-summary(criterion_fw)
par(mfrow=c(2,2))
plot(1:9, res_fw$cp, xlab="No of parameters", ylab="Cp Statistic", main = " Cp Statisticof model from fw")
abline(0,1)
plot(1:9, res_fw$adjr2, xlab="No of parameters", ylab="Adj R2", main = " Adj R2 of model from fw")
plot(1:9, res_fw$rss, xlab="No of parameters", ylab="rss", main = " rss of model from fw")
plot(1:9, res_fw$bic, xlab="No of parameters", ylab="bic", main = " bic of model from fw")
```

From plots, we see for both subsets, the model with all of the variates are the best.


```{r, include=FALSE}
#using the function provided in class, using this way we can see the value for each criterion 
best <- function(model, ...) 
{
  subsets <- regsubsets(formula(model), model.frame(model), ..., nvmax = 10)
  subsets <- with(summary(subsets),
                  cbind(p = as.numeric(rownames(which)), which, rss, rsq, adjr2, cp, bic))
  
  return(subsets)
}  

# Select the 'best' 2 models of all subsets
round(best(model_bw, nbest = 2), 4)

```


```{r}
AIC(model_bw)
AIC(model_fw)
BIC(model_bw)
BIC(model_fw)


````
