---
title: "imaani_code"
author: "Imaani Easthausen"
date: "December 9, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(janitor)
library(readxl)
library(stringr)
library(moments)
library(graphics)
library(MASS)
```

```{r}
hospital_data = read_excel("./data/GHProject_Dataset.xlsx")
```

```{r clean data}  
hospital_data_cleaned = hospital_data %>%
  clean_names() %>%
  dplyr::rename(age = ageyear) %>% 
  
  #remove all NAs from important variables
  filter(!is.na(patientid), !is.na(visitid), !is.na(date), !is.na(losdays2), !is.na(is30dayreadmit), !is.na(mews), !is.na(cindex), !is.na(evisit), !is.na(icu_flag), !is.na(age), !is.na(gender), !is.na(religion), !is.na(maritalstatus), !is.na(race), !is.na(respirationrate), !is.na(bpdiastolic), !is.na(heartrate), !is.na(temperature), !is.na(bpsystolic), !is.na(bmi), !is.na(o2sat)) %>%
  
  #re-classify variables and define factors
  mutate(
    mews = as.factor(ifelse(mews >= 6, 'immediate action', plyr::revalue(as.character(mews), c('0' = "normal", '1' = "normal", '2' = 'increase caution', '3' = 'increase caution', '4' = 'further deterioration', '5' = 'further deterioration')))),
  
    cindex = as.factor(ifelse(cindex >= 5, 'severe', plyr::revalue(as.character(cindex), c('0' = "normal", '1' = "mild", '2' = 'mild', '3' = 'moderate', '4' = 'moderate')))),
    
    religion = as.factor(plyr::revalue(religion, c('Angelican' = "Christian", 'Hebrew' = "Jewish", 'Non Denominational' = 'Other', 'Catholic' = 'Christian', 'Mormon' = 'Other'))),
    
    maritalstatus = as.factor(plyr::revalue(maritalstatus, c('Civil Union' = "Married", 'Divorced' = "Not Married", 'Separated' = 'Not Married', 'Single' = 'Not Married', 'Widowed' = 'Not Married'))),
    
    is30dayreadmit = as.factor(is30dayreadmit),
    
    icu_flag = as.factor(icu_flag), gender = as.factor(gender), race = as.factor(race), facilityname = as.factor(facilityname), insurancetype = as.factor(insurancetype),
    
    mean_arterial_pressure = bpdiastolic + (1/3)*(bpsystolic + bpdiastolic),
    
    o2sat_cat = as.factor(ifelse(o2sat > 95, "normal", "low")),
    
    temperature_cat = as.factor(ifelse(temperature >= 36.1 & temperature <= 37.2, 'normal', ifelse(temperature < 36.1, 'low', 'high'))),
    
    respirationrate_transformed = 1/(respirationrate^2), 
  
    heartrate_transformed = 1/(heartrate^2)
    
    ) %>% 
  
  #transform outcome variable
  mutate(log_length_of_stay = log(losdays2)) %>%

  
  #re-format date variable
  separate(col = admitdtm, into = c("dayofweek", "month_day", "year"), sep = ",") %>%
  mutate(month_day = trimws(month_day), year = trimws(year)) %>%
  separate(col = month_day, into = c("month", "day"), sep = " ") %>%
  mutate(month = plyr::revalue(month, c("January" = '01', "February" = '02', "March" = '03', "April" = '04', "May" = '05', "June" = '06', "July" = '07', "August" = '08', "September" = '09', "October" = '10', "November" = '11', "December" = '12'))) %>%
  mutate(date = str_c(year, month, day, sep = "-")) %>%
  mutate(date = as.Date(date)) %>%
    select(-c(dayofweek, month, day, year, bpsystolic, bpdiastolic)) %>%

  
  #remove subsequent visits for patients with re-admits
  arrange(date) %>%
  filter(!duplicated(patientid)) 


```



```{r exploratory data analysis}
hospital_data_cleaned %>%
  ggplot(aes(x = log_length_of_stay)) +
  geom_histogram()

continuous_predictors_no_transformations = hospital_data_cleaned %>%
  mutate(log_respirationrate = (1/(respirationrate^2))) %>%
  mutate(heartrate_transformed = (1/heartrate^2)) %>%
  select(log_length_of_stay, age, respirationrate, mean_arterial_pressure, o2sat, temperature, heartrate, bmi)

continuous_predictors_w_transformations = hospital_data_cleaned %>%
  select(log_length_of_stay, respirationrate_transformed, heartrate_transformed, bmi)

pairs(continuous_predictors_no_transformations, panel = panel.smooth)

pairs(continuous_predictors_w_transformations, panel = panel.smooth)

hospital_data_cleaned %>%
  select(age, respirationrate_transformed, mean_arterial_pressure, heartrate_transformed, bmi) %>%
  cor() %>%
  kable()

```

```{r export clean dataset}
hospital_data_cleaned %>% write.csv(file = "./data/hospital_data_cleaned.csv")

hospital_data_cleaned %>% 
  select(patientid, visitid, log_length_of_stay, is30dayreadmit, mews, cindex, evisit, icu_flag, age, postalcode, gender, race, religion, maritalstatus, facilityname, insurancetype, bmi, o2sat_cat, temperature_cat, heartrate_transformed, respirationrate_transformed, facilityzip, mean_arterial_pressure, date) %>%
  write.csv(file = "./data/cleaned_data_for_analyses.csv")

```


```{r}
#fit model based on variable selection process
forward_subset = lm(log_length_of_stay ~ is30dayreadmit + cindex + evisit + age + temperature_cat + maritalstatus + insurancetype +  heartrate_transformed + respirationrate_transformed + mean_arterial_pressure, data = hospital_data_cleaned)

stepwise_subset = lm(log_length_of_stay ~ is30dayreadmit + cindex + evisit + age + temperature_cat + insurancetype +  heartrate_transformed + respirationrate_transformed + mean_arterial_pressure , data = hospital_data_cleaned)

anova(stepwise_subset, forward_subset)

plot(forward_subset)

rstandard(forward_subset) %>%
  kurtosis()

rstandard(forward_subset) %>%
  skewness()

residuals = rstandard(forward_subset) 
outlier = residuals[abs(residuals) > 2.5]

hospital_data_cleaned_w_residuals = cbind(hospital_data_cleaned, residuals) %>%
  as.tibble()

is.outlier = function(value, vector){
  value %in% outlier
}

data_no_outliers = hospital_data_cleaned_w_residuals %>%
  mutate(outlier = is.outlier(residuals, outlier))%>%
  filter(outlier == FALSE)

forward_subset2 = lm(log_length_of_stay ~ cindex + evisit + icu_flag + age + gender + religion +  maritalstatus + insurancetype + bmi + o2sat_cat + temperature_transformed + heartrate_transformed + respirationrate_transformed + mean_arterial_pressure, data = data_no_outliers)




what_do_outliers_look_like = hospital_data_cleaned_w_residuals %>%
  mutate(outlier = is.outlier(residuals, outlier))%>%
  filter(outlier == TRUE)

what_do_outliers_look_like %>% write.csv(file = "./data/outlier_patients.csv")




data_no_outliers %>% write.csv(file = "./data/data_no_outliers.csv")


best_subset_no_outliers = lm(log_length_of_stay ~ is30dayreadmit + cindex + evisit + age + gender +
                 maritalstatus + temperature_cat  + heartrate_transformed + respirationrate_transformed + mean_arterial_pressure, data = data_no_outliers )

summary(best_subset_no_outliers)

plot(best_subset_no_outliers)

skewness(rstandard(best_subset_no_outliers))
kurtosis(rstandard(best_subset_no_outliers))







```

































